# core/report.py — session report generator
import os
import re
import datetime
import json
from core.config import get_reports_dir


def generate_report(profile: dict, session_log: list, audit_results: list = None) -> str:
    """Build a plain-English session report. Returns the file path."""
    os.makedirs(get_reports_dir(), exist_ok=True)

    client  = profile.get("client_name", "Unknown Client")
    tech    = profile.get("technician", "Unknown")
    now     = datetime.datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")

    lines = [
        f"UPTEK FIELD REPORT",
        f"Client:     {client}",
        f"Technician: {tech}",
        f"Date:       {date_str} at {time_str}",
        f"{'=' * 60}",
        "",
    ]

    # Open items from profile
    open_items = [i for i in profile.get("open_items", []) if i.get("status") == "open"]
    if open_items:
        lines += ["OPEN ITEMS (carried forward)", ""]
        for item in open_items:
            due = f" [due: {item['due']}]" if item.get("due") else ""
            lines.append(f"  • {item['title']}{due}")
            if item.get("detail"):
                lines.append(f"    {item['detail']}")
        lines.append("")

    # Audit findings
    if audit_results:
        lines += ["AUDIT FINDINGS", ""]
        for r in audit_results:
            sev = r.get("severity", "ok")
            if sev in ("critical", "warning"):
                icon = "🔴" if sev == "critical" else "⚠️"
                lines.append(f"  {icon} {r.get('label')}")
                if r.get("findings"):
                    for f in r["findings"]:
                        lines.append(f"      → {f}")
                if r.get("exposed_ports"):
                    lines.append(f"      → Exposed: {', '.join(r['exposed_ports'])}")
        lines.append("")

    # What was done this session
    session_fixes = [e for e in session_log if e.get("type") == "fix"]
    if session_fixes:
        lines += ["WORK DONE THIS VISIT", ""]
        for fix in session_fixes:
            lines.append(f"  ✅ {fix.get('what')}")
            if fix.get("how"):
                lines.append(f"     {fix.get('how')}")
        lines.append("")

    # New open items created this session
    new_items = [e for e in session_log if e.get("type") == "open_item"]
    if new_items:
        lines += ["NEW ITEMS TO FOLLOW UP", ""]
        for item in new_items:
            due = f" [due: {item.get('due')}]" if item.get("due") else ""
            lines.append(f"  • {item.get('title')}{due}")
            if item.get("detail"):
                lines.append(f"    {item.get('detail')}")
        lines.append("")

    # Tasks run
    tasks_run = [e for e in session_log if e.get("type") == "task"]
    if tasks_run:
        lines += ["TASKS AUTOMATED", ""]
        for t in tasks_run:
            lines.append(f"  ⚡ {t.get('name')}")
        lines.append("")

    lines += [
        f"{'=' * 60}",
        f"Generated by Uptek Field Agent",
        f"906 Tech Express — info@906techexpress.com",
    ]

    content = "\n".join(lines)

    # Save report
    safe_client = re.sub(r"[^a-z0-9_\-]", "", client.lower().replace(" ", "_")).strip("_-") or "unnamed"
    filename = f"{safe_client}_{date_str}.txt"
    path = os.path.join(get_reports_dir(), filename)
    with open(path, "w") as f:
        f.write(content)

    return path


def print_report(path: str):
    with open(path) as f:
        print(f.read())


def generate_html_report(profile: dict, session_log: list, audit_results: list = None,
                         diff: dict = None) -> str:
    """Generate a client-presentable HTML report. Returns the file path."""
    os.makedirs(get_reports_dir(), exist_ok=True)

    client   = profile.get("client_name", "Unknown Client")
    tech     = profile.get("technician", "Unknown")
    now      = datetime.datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")

    SEV_COLOR = {
        "critical": ("#ff4444", "#fff0f0"),
        "warning":  ("#ff9800", "#fff8f0"),
        "info":     ("#2196F3", "#f0f6ff"),
        "ok":       ("#4caf50", "#f0fff0"),
    }
    SEV_ICON = {"critical": "🔴", "warning": "⚠️", "info": "ℹ️", "ok": "✅"}

    def sev_badge(sev):
        color, _ = SEV_COLOR.get(sev, ("#999", "#fff"))
        return f'<span style="background:{color};color:#fff;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:bold">{sev.upper()}</span>'

    findings_html = ""
    if audit_results:
        for r in audit_results:
            sev = r.get("severity", "ok")
            if sev == "ok":
                continue
            color, bg = SEV_COLOR.get(sev, ("#999", "#fff"))
            icon = SEV_ICON.get(sev, "")
            sub = ""
            for f in r.get("findings", []):
                sub += f'<li style="margin:4px 0;color:#555">{f}</li>'
            if r.get("exposed_ports"):
                sub += f'<li>Exposed ports: {", ".join(r["exposed_ports"])}</li>'
            sub_block = f'<ul style="margin:6px 0 0 16px">{sub}</ul>' if sub else ""
            findings_html += f"""
            <div style="border-left:4px solid {color};background:{bg};padding:12px 16px;margin:8px 0;border-radius:4px">
              <strong>{icon} {r.get("label","")}</strong> {sev_badge(sev)}{sub_block}
            </div>"""

    diff_html = ""
    if diff and diff.get("has_previous"):
        new   = diff.get("new", [])
        fixed = diff.get("fixed", [])
        still = diff.get("still_open", [])
        if new:
            items = "".join(f'<li>[{i["severity"].upper()}] {i["label"]}: {i["finding"]}</li>' for i in new)
            diff_html += f'<h3 style="color:#ff4444">🔴 New since last visit</h3><ul>{items}</ul>'
        if fixed:
            items = "".join(f'<li>{i["label"]}: {i["finding"]}</li>' for i in fixed)
            diff_html += f'<h3 style="color:#4caf50">✅ Fixed since last visit</h3><ul>{items}</ul>'
        if still:
            items = "".join(f'<li>[{i["severity"].upper()}] {i["label"]}</li>' for i in still)
            diff_html += f'<h3 style="color:#ff9800">⚠️ Still open from last visit</h3><ul>{items}</ul>'

    open_items = [i for i in profile.get("open_items", []) if i.get("status") == "open"]
    items_html = ""
    for item in open_items:
        due = f' <small style="color:#999">[due: {item["due"]}]</small>' if item.get("due") else ""
        detail = f'<br><small style="color:#666">{item["detail"]}</small>' if item.get("detail") else ""
        items_html += f'<li style="margin:6px 0"><strong>{item["title"]}</strong>{due}{detail}</li>'

    work_html = ""
    for fix in [e for e in session_log if e.get("type") == "fix"]:
        work_html += f'<li>✅ {fix.get("what","")}</li>'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Uptek Field Report — {client}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 860px; margin: 40px auto; padding: 0 24px; color: #222; }}
  h1   {{ color: #111; border-bottom: 3px solid #222; padding-bottom: 8px; }}
  h2   {{ color: #333; margin-top: 32px; }}
  h3   {{ margin: 16px 0 8px; }}
  .meta {{ color: #666; font-size: 14px; margin-bottom: 32px; }}
  .footer {{ margin-top: 48px; padding-top: 16px; border-top: 1px solid #ddd;
             color: #999; font-size: 12px; }}
</style>
</head>
<body>
<h1>Uptek Field Report</h1>
<div class="meta">
  <strong>Client:</strong> {client} &nbsp;|&nbsp;
  <strong>Technician:</strong> {tech} &nbsp;|&nbsp;
  <strong>Date:</strong> {date_str} at {time_str}
</div>

{f'<h2>Visit Changes</h2>{diff_html}' if diff_html else ''}

{f'<h2>Security Findings</h2>{findings_html}' if findings_html else '<p>No significant findings this visit.</p>'}

{f'<h2>Open Items</h2><ul>{items_html}</ul>' if items_html else ''}

{f'<h2>Work Done This Visit</h2><ul>{work_html}</ul>' if work_html else ''}

<div class="footer">
  Generated by Uptek Field Agent &nbsp;|&nbsp; 906 Tech Express &nbsp;|&nbsp; info@906techexpress.com
</div>
</body>
</html>"""

    safe_client = re.sub(r"[^a-z0-9_\-]", "", client.lower().replace(" ", "_")).strip("_-") or "unnamed"
    path = os.path.join(get_reports_dir(), f"{safe_client}_{date_str}.html")
    with open(path, "w") as f:
        f.write(html)
    return path
